USE communityThrive2DB



GO

CREATE TABLE ct2User(
	userID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	roleIDFK INT NOT NULL FOREIGN KEY REFERENCES ct2Role(roleID),
	companyIDFK INT NULL FOREIGN KEY REFERENCES ct2Company(companyID),
	userTypeIDFK INT NULL FOREIGN KEY REFERENCES ct2UserType(userTypeID),
	emailAddress VARCHAR(150)NOT NULL,
	userPassword VARCHAR(150) NOT NULL,
	firstName VARCHAR(100) NOT NULL,
	lastName VARCHAR(100) NOT NULL,
	phoneNumber VARCHAR(100) NULL,
	streetAddress VARCHAR(200) NOT NULL,
	cityIDFK INT NOT NULL FOREIGN KEY REFERENCES ct2City(cityID),
	stateIDFK INT NOT NULL FOREIGN KEY REFERENCES ct2State(stateID),
	zipcode INT NOT NULL
	
	
)

GO


