USE communityThrive2DB



GO

CREATE TABLE ct2User(
	userID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	userAddressIDFK INT FOREIGN KEY REFERENCES ct2Address(addressID),
	roleIDFK INT NOT NULL FOREIGN KEY REFERENCES ct2Role(roleID) DEFAULT 0,
	companyIDFK INT NULL FOREIGN KEY REFERENCES ct2Company(companyID) DEFAULT 0,
	userTypeIDFK INT NULL FOREIGN KEY REFERENCES ct2UserType(userTypeID) DEFAULT 0,
	emailAddress VARCHAR(150)NOT NULL,
	userPassword VARCHAR(150) NOT NULL,
	firstName VARCHAR(100) NOT NULL,
	lastName VARCHAR(100) NOT NULL,
	phoneNumber VARCHAR(100) NULL
	
	
	
)

GO


